### ISSUE TITLE
IGRPWeb Template - Bug Pesquisa passa valor Multi

### ISSUE THREAD

**Issue by ejstavares** [NOSiCode-CV/IGRP-Java-Template-Eclipse#11]
### IGRPWeb Template - Bug Pesquisa passa valor Multi

1- Pesquisa passa valor multi, substitui os que já estavam na lista.

### Passos para reproduzir
- Foi reproduzido um video que pode explicar toda a situação:
<a href="https://share.vidyard.com/watch/JdqoyYmACiGdZbkejDcYNQ?" target="_blanck">Ver Detalhes de BUG</a>

### Informação do Ambiente igrp**web**

* Instancia:   IGRP Web Template
* DAD: 
* Aplicação: 
* Modulo: 
* Pagina: 
* Versão: 

### Qual é o atual comportamento * bug *?
**R:** Pesquisa passa valor, substitui os que já estavam na lista.

### Qual é o comportamento * correto * esperado?
**R:** Ao passar valores Seleccionados, deveria os adicionar na lista aos demais linhas já adicionadas anteriormente.

#### Informação git repository

* user:
* tag version:
* branch:

**Comment by IMarcelF** [comment]
Olá ! 

Não se entende exatamente a lógica de negócio que se pretende implementar. 
Creio que os dados estão a ser substituidos porque fez-se um redirect para a pagina e os dados anteriores não foram guardados ... 

Atentamente., IMF.
