### ISSUE TITLE
 IGRPWeb Template - BUG Quando Radiolist chama função "Remote Combo Box"

### ISSUE THREAD

**Issue by ejstavares** [NOSiCode-CV/IGRP-Java-Template-Eclipse#12]
###  IGRPWeb Template - BUG Quando Radiolist chama função "Remote Combo Box" na "Rules".

1- Sempre passa o valor da 1ª opção para no parâmetro na acção que faz a chamada da função remota.

### Passos para reproduzir
- Foi reproduzido um video que pode explicar toda a situação:
**PS:** No video explicativo a seguir fala de "Remote List", mas se trata de **"Remote Combo Box"**.
[Ver Detalhes de BUG](https://share.vidyard.com/watch/2p9BuD9b4Y74bKSqxHLHng?)

### Informação do Ambiente igrp**web**

* Instancia:   IGRP Web Template
* DAD: 
* Aplicação: 
* Modulo: 
* Pagina: 
* Versão: 

#### Informação git repository

* user:
* tag version:
* branch:

**Comment by IMarcelF** [comment]
Olá ! 

Talvés não tenha uma versão atualizada do igrpweb template na sua máquina; ou estão a ser preenchidos valores iguais para os dois radioButton. 

Best regards., IMF.
