### ISSUE TITLE
IGRP - Educação

### ISSUE THREAD

**Issue by Dnuns** [NOSiCode-CV/IGRP-Java-Template-Eclipse#23]
# IGRP - Educação - proposta de melhorias

Sou professor e usuário da plataforma. Gostaria que implementassem o seguinte: 

-  uma forma de baixar uma lista dos alunos com os campos para preencher as notas;
- quando prontas um meio de fazer upload das notas para o sistema.

Melhores cumprimentos.

**Comment by Isaias1994GitHub** [comment]
Obrigado pelo feedback, mas aqui é somente para issues da plataforma IGRPWEB.

**Comment by Dnuns** [comment]
Olá, então onde devo abrir uma issue sobre o assunto?
