### ISSUE TITLE
Alterar password do utilizador por IGRP SysAdmin

### ISSUE THREAD

**Issue by ejstavares** [NOSiCode-CV/IGRP-Java-Template-Eclipse#25]
**Describe the bug**
Não é possível alterar password de um utilizador, que por acidente esqueceu-se do seu password.

**To Reproduce**
1. Login com super user
2. Click Gestão de Acesso -> Gestão de Utilizador -> Editar
3. De seguida preencher os Inputs "Password" e "Confirmar password"
4. Click Guardar: 
![image](https://user-images.githubusercontent.com/29508261/126069783-993e80b0-5390-43e5-affc-2de7a6ec0907.png)

**OBS**: Em principio retorna uma mensagem "Utilizador atualizado com sucesso.", mas o password não é alterado, ou seja, continua o mesmo que o anterior. Mas é de frisar que se for o próprio User a alterá-lo funciona, mas em caso de perder o password, não possível por esta via.

**Additional**:
`Ainda nesta interface não permite alterar informações do utilizador, sem de preencher os dois inputs de preenchimento obrigatório: "Password" e "Confirmar password".`

**PS:**
`Em caso de houver outras vias, envia a DICA.`

**Comment by Isaias1994GitHub** [comment]
Hello, thank you for the  issue. 
To fix that its just put this config in main.xml... "recover your password" shall show up in ur login and just follow the process.

	<entry key="igrp.pwdRecover">true</entry>
