### ISSUE TITLE
Contribuir

### ISSUE THREAD

**Issue by juaryR** [NOSiCode-CV/IGRP-Java-Template-Eclipse#3]
Como Contribuir com o projecto ? não entendi como posso faze-lo

**Comment by NOSiopen** [comment]
Bom dia,
Neste momento pode contribuir fazendo aplicações com o template e dando inputs de melhorias. Num futuro próximo iremos abrir o código para contribuir no próprio framework.

Caso queira uma conta na nossa cloud, entre em http://store.nosi.cv e comece a fazer aplicações. 
PS: Este template é para ligar IGRP web ao eclipse, mas não é obrigatório.

**Comment by juaryR** [comment]
Uma questão, a  plataforma não é open source ? se sim ela será distribuida sobre qual licança, GPLv3, Apache License 2.0, BSD e MIT. Já existe previsão de liberação do codigo
