### ISSUE TITLE
Missing files building docker image

### ISSUE THREAD

**Issue by angelocorreia27** [NOSiCode-CV/IGRP-Java-Template-Eclipse#40]
Its missing some files for build the docker image.

Missing files in Dockerfile
ADD **tomcat-users.xml** /usr/local/tomcat/conf/ 

ADD **context.xml** /usr/local/tomcat/webapps/manager/META-INF/ 

Command: $ docker build . -t local/igrpweb:local

Error running docker build command:

Step 4/7 : ADD tomcat-users.xml /usr/local/tomcat/conf/
ADD failed: file not found in build context or excluded by .dockerignore: stat tomcat-users.xml: file does not exist
Saving image tar!

**Comment by NOSiopen** [comment]
The tomcat-users.xml and context.xml file are found inside tomcat server. Must be edited according to the tomcat/tomee version
