### ISSUE TITLE
bug: The documentation doesn't render correctly on Firefox

### ISSUE THREAD

**Issue by Dnuns** [NOSiCode-CV/IGRP-Java-Template-Eclipse#43]
**Describe the bug**
The documentation doesn't render correctly on Firefox.

**To Reproduce**
1. Go to 'https://docs.igrp.cv/IGRP/app/webapps?r=tutorial/Listar_documentos/index&dad=tutorial&target=_blank&isPublic=1&lang=pt_PT'
2. Click on 'any menu'
3. See error

**Expected behavior**
The documentation doesn't render correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/51808846/180670873-bd607a67-b93a-4702-a276-af2955eb4463.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Browser [Fireforx]
 - Version [102.0.1 (64-bit)]

**Comment by NOSiopen** [comment]
We are working in a new doc engine. News in a near future
